=== podilaaditya/SensorDataCollector/SensorDataCollector/MetaDataDefinition/schema/ExperimentMetaData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="sdcexperiment" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://schemas.sysnetlab.net/apps/sdc"
	elementFormDefault="qualified">
	
  <xs:element name="experiment">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
        
        <xs:element name="device" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="android" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="make" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="model" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="sdk-int" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="sdk-codename" type="xs:string" minOccurs="1" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="datetimecreation" minOccurs="1" maxOccurs="1"
        	type="xs:dateTime">
        </xs:element>
        
        <xs:element name="datetimecompletion" minOccurs="1"
        	maxOccurs="1" type="xs:dateTime">
        </xs:element>
        
        <xs:element name="taglist" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tag" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="shortdescription" type="xs:string" minOccurs="0" />
                    <xs:element name="longdescription" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="notelist" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="note" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="notetext" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="datetime" type="xs:dateTime" minOccurs="1"
                    	maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="taggingactionlist" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="taggingaction" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tagreference" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="experimenttime" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="threadtimemillis"
                          	type="xs:long" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="elapsedrealtime" type="xs:long" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="elapsedrealtimenanos" type="xs:long" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="taggingstate" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="sensorlist" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sensor" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="majortype" type="xs:int" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="minortype" type="xs:int" minOccurs="1" maxOccurs="1"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<xs:element name="sensordata">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="experiment">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datadescription">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sensor" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="definition" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="location" nillable="true" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="type" type="xs:string" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="column" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:string" />
                        <xs:attribute name="pos" type="xs:string" />
                        <xs:attribute name="type" type="xs:string" />
                        <xs:attribute name="description" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>  
</xs:schema>

=== podilaaditya/SensorDataCollector/SensorDataCollector/MetaDataDefinition/example/ExperimentMetaExample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<experiment xmlns="http://schemas.sysnetlab.net/apps/sdc"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sysnetlab.net/apps/sdc ExperimentMetaData.xsd">
	
	<name>
	    unnamed experiment
	</name>
	
	<device>
		<android>
			<make>Google</make>
			<model>Nexus 2000</model>
			<sdk-int>9</sdk-int>
			<sdk-codename>GINGERBREAD</sdk-codename>
		</android>
	</device>

	<datetimecreation>
	    2014-05-30T09:30:10.535Z
	</datetimecreation>

	<datetimecompletion>
	    2014-05-30T09:45:14.123Z
	</datetimecompletion>

	<taglist>
		<tag>
			<name>Run</name>
			<shortdescription>Chicken run</shortdescription>
			<longdescription>Chicken run and run</longdescription>
		</tag>
		<tag>
			<name>Walk</name>
			<shortdescription>Clown walk</shortdescription>
			<longdescription>Clown walk and walk</longdescription>
		</tag>
	</taglist>
	
	<notelist>
		<note>
			<notetext>
				this is the 1st note.
			</notetext>
		    <datetime>
	    		2014-05-30T09:30:10.535Z
			</datetime>
		</note>
		<note>
			<notetext>
				this is the 2nd note.
			</notetext>
		    <datetime>
	    		2014-05-30T09:31:10.535Z
			</datetime>
		</note>
	</notelist>
	
	<taggingactionlist>
		<taggingaction>
			<tagreference name="Run"/>
			<experimenttime>
				<threadtimemillis>199</threadtimemillis>
				<elapsedrealtime>201</elapsedrealtime>
				<elapsedrealtimenanos>199001</elapsedrealtimenanos>
			</experimenttime>
			<taggingstate>
				<name>TAG_ON</name>
			</taggingstate>
		</taggingaction>
		<taggingaction>
			<tagreference name="Run"/>
			<experimenttime>
				<threadtimemillis>199</threadtimemillis>
				<elapsedrealtime>201</elapsedrealtime>
				<elapsedrealtimenanos>199001</elapsedrealtimenanos>
			</experimenttime>
			<taggingstate>
				<name>TAG_OFF</name>
			</taggingstate>
		</taggingaction>
	</taggingactionlist>
	
	<sensorlist>
		<sensor id="0">
			<name>goldfish acceleration sensor</name>
			<majortype>1</majortype>
			<minortype>2</minortype>
		</sensor>
		<sensor id="1">
			<name>goldfish proximity sensor</name>
			<majortype>1</majortype>
			<minortype>3</minortype>
		</sensor>
	</sensorlist>
</experiment>
