=== podilaaditya/SensorDataCollector/SensorDataCollectorXML/XSD/ExperimentMetaData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="sdcexperiment" 
	xmlns="" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
	
  <xs:element name="datetime">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="year" type="xs:string" minOccurs="0" msdata:Ordinal="0" />
        <xs:element name="month" type="xs:string" minOccurs="0" msdata:Ordinal="1" />
        <xs:element name="day" type="xs:string" minOccurs="0" msdata:Ordinal="2" />
        <xs:element name="hour" type="xs:string" minOccurs="0" msdata:Ordinal="3" />
        <xs:element name="minute" type="xs:string" minOccurs="0" msdata:Ordinal="4" />
        <xs:element name="second" type="xs:string" minOccurs="0" msdata:Ordinal="5" />
        <xs:element name="millisecond" type="xs:string" minOccurs="0" msdata:Ordinal="6" />
      </xs:sequence>
      <xs:attribute name="locale" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="experiment">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string" minOccurs="0" />
        <xs:element name="device" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="android" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="make" type="xs:string" minOccurs="0" />
                    <xs:element name="model" type="xs:string" minOccurs="0" />
                    <xs:element name="sdk-int" type="xs:string" minOccurs="0" />
                    <xs:element name="sdk-codename" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datetimecreation" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="datetime" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datetimecompletion" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="datetime" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="taglist" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tag" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" minOccurs="0" />
                    <xs:element name="shortdescription" type="xs:string" minOccurs="0" />
                    <xs:element name="shortdescriptioin" type="xs:string" minOccurs="0" />
                    <xs:element name="longdescription" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="notelist" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="note" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="notetext" type="xs:string" minOccurs="0" />
                    <xs:element ref="datetime" minOccurs="0" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="taggingactionlist" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="taggingaction" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tagreference" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="experimenttime" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="threadtimemillis" type="xs:string" minOccurs="0" />
                          <xs:element name="elapsedrealtime" type="xs:string" minOccurs="0" />
                          <xs:element name="elapsedrealtimenanos" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="taggingstate" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="sensorlist" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sensor" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" minOccurs="0" msdata:Ordinal="0" />
                    <xs:element name="majortype" type="xs:string" minOccurs="0" msdata:Ordinal="1" />
                    <xs:element name="minortype" type="xs:string" minOccurs="0" msdata:Ordinal="2" />
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<xs:element name="sensordata" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="experiment">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datadescription">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sensor" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent msdata:ColumnName="sensor_Text" msdata:Ordinal="1">
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="definition" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="location" nillable="true" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent msdata:ColumnName="location_Text" msdata:Ordinal="1">
                          <xs:extension base="xs:string">
                            <xs:attribute name="type" type="xs:string" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="column" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:string" />
                        <xs:attribute name="pos" type="xs:string" />
                        <xs:attribute name="type" type="xs:string" />
                        <xs:attribute name="description" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>  
  <xs:element name="sdcexperiment" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="datetime" />
        <xs:element ref="experiment" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== podilaaditya/SensorDataCollector/SensorDataCollectorXML/XML/ExperimentMetaExample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<experiment xmlns="http://schemas.sysnetlab.net/apps/sdc"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sysnetlab.net/apps/sdc ExperimentMetaData.xsd">    
	
	<name>
	    unnamed experiment
	</name>
	
	<device>
		<android>
			<make>Google</make>
			<model>Nexus 2000</model>
			<sdk-int>9</sdk-int>
			<sdk-codename>GINGERBREAD</sdk-codename>
		</android>
	</device>

	<datetimecreation>
		<datetime locale="US">
			<year>2014</year>
			<month>5</month>
			<day>28</day>
			<hour>18</hour>
			<minute>44</minute>
			<second>11</second>
			<millisecond>234</millisecond>
		</datetime>
	</datetimecreation>

	<datetimecompletion>
		<datetime locale="US">
			<year>2014</year>
			<month>5</month>
			<day>28</day>
			<hour>18</hour>
			<minute>48</minute>
			<second>11</second>
			<millisecond>234</millisecond>
		</datetime>
	</datetimecompletion>

	<taglist>
		<tag>
			<name>Run</name>
			<shortdescriptioin>Chicken run</shortdescriptioin>
			<longdescription>Chicken run and run</longdescription>
		</tag>
		<tag>
			<name>Walk</name>
			<shortdescription>Clown walk</shortdescription>
			<longdescription>Clown walk and walk</longdescription>
		</tag>
	</taglist>
	
	<notelist>
		<note>
			<datetime locale="US">
				<year>2014</year>
				<month>5</month>
				<day>28</day>
				<hour>18</hour>
				<minute>44</minute>
				<second>11</second>
				<millisecond>234</millisecond>
			</datetime>
			<notetext>
				this is a note.
			</notetext>
		</note>
		<note>
			<datetime locale="US">
				<year>2014</year>
				<month>5</month>
				<day>28</day>
				<hour>18</hour>
				<minute>45</minute>
				<second>11</second>
				<millisecond>234</millisecond>
			</datetime>
			<notetext>
				this is a note.
			</notetext>
		</note>
	</notelist>
	
	<taggingactionlist>
		<taggingaction>
			<tagreference name="Run"/>
			<experimenttime>
				<threadtimemillis>199</threadtimemillis>
				<elapsedrealtime>201</elapsedrealtime>
				<elapsedrealtimenanos>199001</elapsedrealtimenanos>
			</experimenttime>
			<taggingstate>
				<name>TAG_ON</name>
			</taggingstate>
		</taggingaction>
		<taggingaction>
			<tagreference name="Run"/>
			<experimenttime>
				<threadtimemillis>199</threadtimemillis>
				<elapsedrealtime>201</elapsedrealtime>
				<elapsedrealtimenanos>199001</elapsedrealtimenanos>
			</experimenttime>
			<taggingstate>
				<name>TAG_OFF</name>
			</taggingstate>
		</taggingaction>
	</taggingactionlist>
	
	<sensorlist>
		<sensor id="0">
			<name>goldfish acceleration sensor</name>
			<majortype>1</majortype>
			<minortype>2</minortype>
		</sensor>
		<sensor id="1">
			<name>goldfish proximity sensor</name>
			<majortype>1</majortype>
			<minortype>3</minortype>
		</sensor>
	</sensorlist>
</experiment>

=== podilaaditya/SensorDataCollector/SensorDataCollectorXML/XML/ExperimentSensorDataExample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<sensordata xmlns="http://schemas.sysnetlab.net/apps/sdc"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sysnetlab.net/apps/sdc ExperimentMetaData.xsd">    
    <experiment>
        <name>Unnamed Experiment</name>
    </experiment>
    <datadescription>
        <sensor id="0">goldfish acceleration sensor</sensor>
        <definition>
            <location type="csv">goldfish_acceleration_sensor.txt</location>
            <column id="0" pos="0" type="long" description="threadtimemillis"/>
            <column id="1" pos="1" type="long" description="elapsedrealtime"/>
            <column id="2" pos="2" type="long" description="elapsedrealtimenanos"/>
            <column id="3" pos="3" type="double" description="value"/>
            <column id="4" pos="4" type="double" description="value"/>
            <column id="5" pos="5" type="double" description="value"/>
        </definition>
    </datadescription>
</sensordata>
